server:
  port: 8120


spring:
  profiles:
    active: dev

  # redis 配置
  data:
    redis:
      host: ${E_DOVE_DOCKER_IP_ADDR}
      port: 6379
      password: eDoveRedis1014

  # mysql 配置
  datasource:
    url: jdbc:mysql://${E_DOVE_DOCKER_IP_ADDR}:3306/e_dove_user?characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: e_dove_user_admin
    password: eDoveMysql1014
    driver-class-name: com.mysql.cj.jdbc.Driver

# 日志级别
logging:
  level:
    com.criel.edove.user.mapper: trace

# 自定义配置
edove:
  # 雪花算法配置
  snowflake:
    data-center-id: 2 # 数据中心ID
    worker-id: 2 # 机器ID

  # 身份码条形码配置
  identity-barcode:
    width: 500
    height: 150
    ttl: 5 # 单位：分钟
    key: eDoveBarcodeKey1014
    algorithm: HmacSHA256 # 签名算法
    signLength: 6 # 签名截取长度