server:
  port: 8120

spring:
  application:
    name: e-dove-user

  cloud:
    # nacos 配置
    nacos:
      discovery:
        server-addr: ${E_DOVE_DOCKER_IP_ADDR}
        namespace: ${E_DOVE_NACOS_NAMESPACE}
      config:
        server-addr: ${E_DOVE_DOCKER_IP_ADDR}
        namespace: ${E_DOVE_DOCKER_IP_ADDR}
        file-extension: properties

  data:
    # redis配置
    redis:
      host: ${E_DOVE_DOCKER_IP_ADDR}
      port: 6379
      password: eDoveRedis1014

# 自定义配置
edove:
  # jwt配置
  jwt:
    # access token
    access-key: "Q3JpZWxFRG92ZUp3dEFjY2Vzc1Rva2VuS2V5MTIzNDU="
    access-ttl: 3600000 # 1小时

    # refresh token
    refresh-key: "Q3JpZWxFRG92ZUp3dFJlZnJlc2hUb2tlbktleTEyMzQ="
    refresh-ttl: 604800000 # 7天

  # 雪花算法配置
  snowflake:
    data-center-id: 1001 # 数据中心ID
    worker-id: 1001 # 机器ID